name: GraphCDN
on:
  push:
    branches:
      - main
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          check-latest: true

      - name: Push schema
        run: npx stellate push --service bookclub
        env:
          STELLATE_TOKEN: ${{ secrets.GRAPHCDN_CI_TOKEN }}
